name: 'container-ssh-agent'
description: 'Run `container-ssh-agent` and load an SSH key to access other private repositories inspired by ssh-agent'
inputs:
    ssh-private-key:
        description: 'Private SSH key to register in the SSH agent'
        required: true
    ssh-auth-sock:
        required: false
        description: 'Where to place the SSH Agent auth socket'
    home-dir:
        required: false
        description: 'Explicit home directory to support containers'
runs:
    using: 'node12'
    main: 'dist/index.js'
    post: 'dist/cleanup.js'
branding:
    icon: loader
    color: 'yellow'
